In [13]:
import pandas as pd
import geopandas as gpd
from shapely import wkt
from shapely.geometry import Point
import plotly.express as px
import plotly.io as pio
pio.renderers.default = "notebook"

In [27]:
crimes = pd.read_csv('data/locations/crimes.csv')
crimes['Geometry'] = crimes.apply(lambda r: Point(r[['Longitude', 'Latitude']]), axis=1)
crimes = gpd.GeoDataFrame(crimes).set_geometry('Geometry').set_crs(epsg=4326).to_crs(epsg=26986)
crimes

/var/folders/s2/j51485yj36jd10p_lm_r9l_00000gn/T/ipykernel_91113/849578695.py:1: DtypeWarning:

Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.

,ID,OFFENSE_CODE_GROUP,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,STREET,Latitude,Longitude,Location,Geometry
0,I172040657,Harassment,2015-06-15 00:00:00,2015,6,Monday,MELBOURNE ST,42.291093,-71.065945,"(42.29109287, -71.06594539)",POINT (235796.012 893492.730)
1,I152049588,Larceny From Motor Vehicle,2015-06-15 00:01:00,2015,6,Monday,CONCORD SQ,42.341384,-71.078989,"(42.34138415, -71.07898883)",POINT (234692.770 899073.410)
2,I152049463,Vandalism,2015-06-15 00:03:00,2015,6,Monday,LEXINGTON AVE,42.262551,-71.115822,"(42.26255067, -71.11582205)",POINT (231697.047 890302.713)
3,I152049469,Simple Assault,2015-06-15 00:45:00,2015,6,Monday,BAGNAL ST,42.359569,-71.135982,"(42.35956890, -71.13598188)",POINT (229987.757 901071.679)
4,I152049479,Simple Assault,2015-06-15 01:30:00,2015,6,Monday,COMMONWEALTH AVE,42.350740,-71.130479,"(42.35073963, -71.13047909)",POINT (230445.322 900092.911)
...,...,...,...,...,...,...,...,...,...,...,...
302913,232061909,Larceny,2023-08-04 17:09:00,2023,8,Friday,NORFOLK ST,42.284579,-71.080834,"(42.28457938304387, -71.08083375845698)",POINT (234571.750 892763.111)
302914,232066199,Vandalism,2023-08-18 17:50:00,2023,8,Friday,JUDSON ST,42.319501,-71.075165,"(42.31950147916197, -71.07516529856777)",POINT (235019.946 896644.362)
302915,232067269,Larceny,2023-08-22 15:07:00,2023,8,Tuesday,HUNTINGTON AVE,42.347309,-71.079152,"(42.34730934597846, -71.07915218290486)",POINT (234676.062 899731.485)
302916,232070395,Robbery,2023-09-01 13:18:00,2023,9,Friday,UNION ST,42.360687,-71.056873,"(42.36068738800536, -71.05687337090743)",POINT (236504.005 901226.750)
302917,232071422,Motor Vehicle Accident Response,2023-09-04 21:42:00,2023,9,Monday,COMMONWEALTH AVE,42.347953,-71.136308,"(42.34795320232855, -71.1363080075282)",POINT (229966.392 899781.343)

In [56]:
crimes['OCCURRED_ON_DATE'] = pd.to_datetime(crimes['OCCURRED_ON_DATE'])
NUM_YEARS = (crimes['OCCURRED_ON_DATE'].max() - crimes['OCCURRED_ON_DATE'].min()).days / 365.25
NUM_YEARS

8.643394934976044

In [28]:
open_spaces = pd.read_csv('data/locations/open_spaces.csv')
open_spaces['Geometry'] = open_spaces['Geometry'].apply(wkt.loads)
open_spaces = gpd.GeoDataFrame(open_spaces).set_geometry('Geometry').set_crs(epsg=4326).to_crs(epsg=26986)
open_spaces

,SPACEID,Name,Type,Acres,Geometry,Avg. Lat,Avg. Long,Lat Range,Long Range
0,1,Wilson Park,"Malls, Squares & Plazas",0.097184,"MULTIPOLYGON (((229183.865 898997.312, 229168....",42.340991,-71.145929,0.000171,0.000352
1,2,James H. Roberts Playground,Playgrounds,1.004136,"MULTIPOLYGON (((230878.004 901037.246, 230855....",42.359526,-71.125332,0.000798,0.001071
2,3,Smith Playground,Playgrounds,15.025247,"MULTIPOLYGON (((230387.837 901474.134, 230368....",42.365072,-71.131046,0.003792,0.003269
3,4,Fern Square,"Malls, Squares & Plazas",0.044509,"MULTIPOLYGON (((230199.465 901062.644, 230219....",42.359534,-71.133291,0.000186,0.000243
4,5,Ringer Playground,Playgrounds,10.263093,"MULTIPOLYGON (((229950.853 900128.016, 229948....",42.350456,-71.138129,0.002734,0.003772
...,...,...,...,...,...,...,...,...,...
529,530,Mahoney Park,Parks,0.381102,"MULTIPOLYGON (((236976.036 899146.767, 236953....",42.342008,-71.051382,0.000587,0.000750
530,531,Boundary I,Urban Wilds,6.925776,"MULTIPOLYGON (((229994.695 891116.623, 229848....",42.269348,-71.137990,0.002408,0.003154
531,1340,Sprague Pond,Urban Wilds,1.196202,"MULTIPOLYGON (((229839.392 887071.287, 229895....",42.233786,-71.138006,0.001224,0.000994
532,2541,Codman Square,"Malls, Squares & Plazas",0.350710,"MULTIPOLYGON (((235394.782 893417.133, 235391....",42.290418,-71.071082,0.000368,0.000891
533,2940,Murphy Playground I,Playgrounds,2.449197,"MULTIPOLYGON (((231922.424 895334.558, 231932....",42.307341,-71.113440,0.001003,0.001483

In [36]:
open_spaces['Crimes'] = open_spaces['Geometry'].apply(lambda x: (crimes['Geometry'].distance(x) <= 500).sum())
open_spaces

,SPACEID,Name,Type,Acres,Geometry,Avg. Lat,Avg. Long,Lat Range,Long Range,Crimes
0,1,Wilson Park,"Malls, Squares & Plazas",0.097184,"MULTIPOLYGON (((229183.865 898997.312, 229168....",42.340991,-71.145929,0.000171,0.000352,1517
1,2,James H. Roberts Playground,Playgrounds,1.004136,"MULTIPOLYGON (((230878.004 901037.246, 230855....",42.359526,-71.125332,0.000798,0.001071,601
2,3,Smith Playground,Playgrounds,15.025247,"MULTIPOLYGON (((230387.837 901474.134, 230368....",42.365072,-71.131046,0.003792,0.003269,790
3,4,Fern Square,"Malls, Squares & Plazas",0.044509,"MULTIPOLYGON (((230199.465 901062.644, 230219....",42.359534,-71.133291,0.000186,0.000243,1240
4,5,Ringer Playground,Playgrounds,10.263093,"MULTIPOLYGON (((229950.853 900128.016, 229948....",42.350456,-71.138129,0.002734,0.003772,4811
...,...,...,...,...,...,...,...,...,...,...
529,530,Mahoney Park,Parks,0.381102,"MULTIPOLYGON (((236976.036 899146.767, 236953....",42.342008,-71.051382,0.000587,0.000750,5083
530,531,Boundary I,Urban Wilds,6.925776,"MULTIPOLYGON (((229994.695 891116.623, 229848....",42.269348,-71.137990,0.002408,0.003154,165
531,1340,Sprague Pond,Urban Wilds,1.196202,"MULTIPOLYGON (((229839.392 887071.287, 229895....",42.233786,-71.138006,0.001224,0.000994,178
532,2541,Codman Square,"Malls, Squares & Plazas",0.350710,"MULTIPOLYGON (((235394.782 893417.133, 235391....",42.290418,-71.071082,0.000368,0.000891,4456
533,2940,Murphy Playground I,Playgrounds,2.449197,"MULTIPOLYGON (((231922.424 895334.558, 231932....",42.307341,-71.113440,0.001003,0.001483,1774

In [57]:
open_spaces['Nearby Crimes Per Year'] = open_spaces['Crimes'] / NUM_YEARS

In [58]:
open_spaces.to_csv('data/locations/open_spaces_with_crimes.csv', index=False)